export function shuffleArr(arr) {
    const a = [...arr]; for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1));[a[i], a[j]] = [a[j], a[i]]; } return a;
}

export const CHAPTERS = {
    eamcet: [
        "Physics — Mechanics", "Physics — Waves & Sound", "Physics — Optics", "Physics — Thermodynamics", "Physics — Electromagnetism",
        "Chemistry — Atomic Structure", "Chemistry — Organic Chemistry", "Chemistry — Physical Chemistry", "Chemistry — Inorganic Chemistry",
        "Maths — Algebra", "Maths — Calculus", "Maths — Integration", "Maths — Trigonometry", "Maths — Coordinate Geometry", "Maths — Vectors"
    ],
    it: [
        "Python Basics", "Data Types & Variables", "Control Flow", "Functions & Modules", "OOP Concepts",
        "SQL Basics", "Advanced SQL", "Relational Databases",
        "HTML & CSS", "JavaScript Basics", "React Foundation",
        "Data Structures — Arrays & Linked Lists", "Data Structures — Trees & Graphs",
        "Algorithm — Sorting & Searching", "Algorithm — Dynamic Programming",
        "Git & Version Control", "Computer Networks", "Operating Systems"
    ],
    diploma: [
        "Electrical Fundamentals", "DC Circuits", "Transformers", "AC Machines", "Power Systems",
        "Engineering Materials", "Fluid Mechanics", "Thermodynamics Basics",
        "Workshop Safety", "AutoCAD Basics", "Engineering Drawing", "Manufacturing Processes"
    ],
    neet: [
        "Cell Biology", "Genetics & Heredity", "Human Digestive System", "Respiration", "Human Circulation", "Neural Control",
        "Plant Physiology", "Ecology & Environment", "Biotechnology",
        "Organic Chemistry", "Inorganic Chemistry", "Physical Chemistry"
    ],
    appsc: [
        "Indian History", "Andhra Pradesh History",
        "Indian Geography", "AP Geography",
        "Indian Polity", "AP Economy",
        "General Science", "Current Affairs (National)", "Current Affairs (Regional)",
        "Maths — Arithmetic", "Logical Reasoning", "Data Interpretation"
    ]
};

export const QBANKS_RAW = {
    eamcet: [
        { s: "Physics", b: "A body thrown vertically upward with velocity u. Max height:", o: ["u/g", "u²/2g", "u²/g", "2u²/g"], a: 1, e: "Using equation of motion v² = u² - 2gh (v=0 at max height), h = u²/2g" },
        { s: "Physics", b: "Newton's 3rd Law states:", o: ["F=ma", "Every action has equal & opposite reaction", "Objects at rest stay at rest", "Energy is conserved"], a: 1, e: "Newton's 3rd Law is about action and reaction forces being equal and opposite." },
        { s: "Physics", b: "Unit of electric field:", o: ["N/C", "C/N", "J/C", "V·m"], a: 0, e: "Electric field is defined as Force per unit charge (E = F/q), so Newton/Coulomb." },
        { s: "Chemistry", b: "Noble gas example:", o: ["Nitrogen", "Oxygen", "Argon", "Chlorine"], a: 2, e: "Argon is a chemically inert Group 18 element, making it a noble gas." },
        { s: "Chemistry", b: "pH of neutral solution:", o: ["0", "7", "14", "1"], a: 1, e: "On the pH scale of 0 to 14, 7 represents a perfectly neutral solution (like pure water)." },
        { s: "Chemistry", b: "Bond in NaCl:", o: ["Covalent", "Ionic", "Metallic", "Hydrogen"], a: 1, e: "Na transfers an electron to Cl, creating positive and negative ions that attract each other (Ionic Bond)." },
        { s: "Mathematics", b: "sin θ = 3/5, cos θ =", o: ["4/5", "5/4", "3/4", "5/3"], a: 0, e: "Using the Pythagorean identity sin²θ + cos²θ = 1. So, cosθ = √(1 - (3/5)²) = 4/5." },
        { s: "Mathematics", b: "Derivative of sin(x):", o: ["-cos(x)", "cos(x)", "-sin(x)", "tan(x)"], a: 1, e: "The standard derivative of sin(x) is cos(x)." },
        { s: "Mathematics", b: "Sum of first n natural numbers:", o: ["n(n+1)", "n(n-1)/2", "n(n+1)/2", "n²"], a: 2, e: "The arithmetic progression sum formula for the first n natural numbers is n(n+1)/2." },
        { s: "Physics", b: "Speed of light in vacuum:", o: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"], a: 0, e: "The speed of light in a vacuum (c) is exactly 299,792,458 m/s, usually approximated as 3×10⁸ m/s." },
        { s: "Physics", b: "Unit of power is:", o: ["Joule", "Watt", "Newton", "Pascal"], a: 1, e: "Power is the rate of doing work, measured in Joules per second, which is equivalent to Watts." },
        { s: "Chemistry", b: "Formula for Sulfuric Acid:", o: ["HCl", "H2SO4", "HNO3", "H2O"], a: 1, e: "Sulfuric acid formula is H₂SO₄, composed of hydrogen, sulfur, and oxygen." },
        { s: "Mathematics", b: "Integral of x:", o: ["x", "1", "x^2 / 2", "0"], a: 2, e: "Using the power rule for integration ∫x^n dx = (x^(n+1))/(n+1). For n=1, it is x²/2." },
        { s: "Physics", b: "Resistance in parallel formula:", o: ["R1+R2", "R1-R2", "1/R1 + 1/R2 = 1/R", "R1*R2"], a: 2, e: "In a parallel circuit, the reciprocal of total resistance equals the sum of the reciprocals of individual resistances." },
        { s: "Chemistry", b: "Most abundant gas in atmosphere:", o: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"], a: 1, e: "Nitrogen makes up approximately 78% of the Earth's atmosphere." },
        { s: "Physics", b: "Dimensional formula of work:", o: ["ML²T⁻²", "MLT⁻²", "ML²T⁻¹", "MLT⁻¹"], a: 0, e: "Work = Force × Distance = [MLT⁻²][L] = ML²T⁻²" },
        { s: "Physics", b: "Snell's law relates to:", o: ["Diffraction", "Refraction", "Reflection", "Polarisation"], a: 1, e: "Snell's law describes the relationship between angles of incidence and refraction when light passes between media." },
        { s: "Physics", b: "SI unit of frequency:", o: ["Watt", "Hertz", "Pascal", "Joule"], a: 1, e: "Frequency is measured in Hertz (Hz), representing cycles per second." },
        { s: "Chemistry", b: "Avogadro's number is approximately:", o: ["6.022 × 10²³", "6.022 × 10²²", "3.14 × 10²³", "1.6 × 10⁻¹⁹"], a: 0, e: "Avogadro's number is 6.022 × 10²³, representing the number of entities in one mole." },
        { s: "Chemistry", b: "Which element has atomic number 1?", o: ["Helium", "Hydrogen", "Lithium", "Carbon"], a: 1, e: "Hydrogen has atomic number 1, meaning it has one proton in its nucleus." },
        { s: "Chemistry", b: "Oxidation involves:", o: ["Gain of electrons", "Loss of electrons", "Gain of protons", "Loss of neutrons"], a: 1, e: "Oxidation is defined as the loss of electrons. Remember OIL RIG: Oxidation Is Loss." },
        { s: "Mathematics", b: "log₁₀(1000) =", o: ["2", "3", "4", "10"], a: 1, e: "log₁₀(1000) = log₁₀(10³) = 3" },
        { s: "Mathematics", b: "Value of tan 45°:", o: ["0", "1", "√3", "1/√3"], a: 1, e: "tan 45° = sin 45° / cos 45° = 1." },
        { s: "Mathematics", b: "Roots of x² - 5x + 6 = 0:", o: ["2, 3", "1, 6", "-2, -3", "3, -2"], a: 0, e: "Factoring: (x-2)(x-3) = 0, so x = 2 or x = 3." },
        { s: "Physics", b: "Ohm's Law formula:", o: ["V = IR", "V = I/R", "V = R/I", "I = VR"], a: 0, e: "Ohm's Law states Voltage (V) = Current (I) × Resistance (R)." },
        { s: "Physics", b: "Acceleration due to gravity on Earth:", o: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "6.67 m/s²"], a: 1, e: "The standard acceleration due to gravity on Earth's surface is approximately 9.8 m/s²." },
        { s: "Chemistry", b: "Water molecule has how many hydrogen atoms?", o: ["1", "2", "3", "4"], a: 1, e: "Water (H₂O) consists of 2 hydrogen atoms and 1 oxygen atom." },
        { s: "Mathematics", b: "Area of a circle with radius r:", o: ["2πr", "πr²", "πd", "2πr²"], a: 1, e: "The area of a circle is given by the formula A = πr²." },
        { s: "Physics", b: "Which lens is used to correct myopia?", o: ["Convex", "Concave", "Bifocal", "Cylindrical"], a: 1, e: "Concave (diverging) lens is used to correct myopia (near-sightedness) by diverging light rays before they enter the eye." },
        { s: "Chemistry", b: "Isotopes differ in number of:", o: ["Protons", "Electrons", "Neutrons", "Positrons"], a: 2, e: "Isotopes of an element have the same number of protons but different numbers of neutrons." }
    ],
    it: [
        { s: "Programming", b: "CPU stands for:", o: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Control Processing Unit"], a: 0, e: "CPU stands for Central Processing Unit, acting as the brain of the computer." },
        { s: "Programming", b: "LIFO data structure:", o: ["Queue", "Stack", "Array", "Linked List"], a: 1, e: "Stack follows Last-In-First-Out (LIFO), where the last added element is the first to be removed." },
        { s: "Programming", b: "print(2**3) in Python:", o: ["6", "8", "9", "5"], a: 1, e: "The ** operator in Python stands for exponentiation. 2 to the power of 3 is 8." },
        { s: "Programming", b: "Binary search complexity:", o: ["O(n)", "O(n²)", "O(log n)", "O(1)"], a: 2, e: "Binary search halves the search space at each step, resulting in logarithmic O(log n) time complexity." },
        { s: "Networking", b: "HTTP stands for:", o: ["Hyper Text Transfer Protocol", "High Tech Transfer Protocol", "Hyper Tech Text Protocol", "Hyper Transfer Text Protocol"], a: 0, e: "HTTP (Hyper Text Transfer Protocol) is the foundation of data communication for the World Wide Web." },
        { s: "Database", b: "SQL stands for:", o: ["Structured Query Language", "Simple Query Language", "System Query Language", "Standard Query Logic"], a: 0, e: "SQL is a standardized programming language that is used to manage relational databases." },
        { s: "Programming", b: "Python function keyword:", o: ["function", "define", "def", "func"], a: 2, e: "Python uses the 'def' keyword to define a block of code as a function." },
        { s: "Programming", b: "OOP stands for:", o: ["Object Oriented Programming", "Open Online Platform", "Object Operating Program", "Ordered Operations Protocol"], a: 0, e: "Object Oriented Programming (OOP) organizes software design around data, or objects, rather than functions and logic." },
        { s: "Networking", b: "DNS converts:", o: ["IP to MAC", "Domain names to IP", "Data to binary", "HTTP to HTTPS"], a: 1, e: "Domain Name System (DNS) acts as the phonebook of the internet, translating human readable domain names to IP addresses." },
        { s: "Programming", b: "Git is used for:", o: ["Database management", "Version control", "Web hosting", "Email services"], a: 1, e: "Git is a distributed version control system for tracking changes in source code during software development." },
        { s: "Programming", b: "Time complexity of bubble sort:", o: ["O(n)", "O(log n)", "O(n²)", "O(1)"], a: 2, e: "In the worst case, bubble sort compares every pair of elements, requiring n×n operations (O(n²))." },
        { s: "Database", b: "SQL command to get all columns:", o: ["SELECT EVERY", "SELECT *", "GET ALL", "FETCH *"], a: 1, e: "The asterisk (*) acts as a wildcard in SELECT statements to fetch all columns from a table." },
        { s: "Programming", b: "What is JS NaN?", o: ["Not a Null", "Not a Number", "Now a Number", "New array Notation"], a: 1, e: "NaN stands for Not-a-Number, representing a value which is not a valid number in JavaScript." },
        { s: "Networking", b: "Port for HTTPS:", o: ["80", "21", "22", "443"], a: 3, e: "Port 443 is the standard port for secure HTTPS web traffic over TLS/SSL." },
        { s: "Programming", b: "Java runs on:", o: ["V8 Engine", "JRE/JVM", ".NET Framework", "LLVM"], a: 1, e: "Java code is compiled into bytecode, which is executed by the Java Virtual Machine (JVM) inside the JRE." },
        { s: "Programming", b: "Which keyword is used for inheritance in Java?", o: ["implements", "inherits", "extends", "super"], a: 2, e: "In Java, 'extends' keyword is used to inherit properties and methods from a parent class." },
        { s: "Programming", b: "What does CSS stand for?", o: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Colorful Style Sheets"], a: 1, e: "CSS stands for Cascading Style Sheets, used for describing the presentation of HTML documents." },
        { s: "Database", b: "Primary key in a database must be:", o: ["Nullable", "Unique", "Foreign", "Indexed only"], a: 1, e: "A primary key must be unique and not null, uniquely identifying each record in a table." },
        { s: "Programming", b: "Which protocol is used for email sending?", o: ["FTP", "SMTP", "HTTP", "SSH"], a: 1, e: "SMTP (Simple Mail Transfer Protocol) is used for sending email messages between servers." },
        { s: "Programming", b: "What is the output of: bool('') in Python?", o: ["True", "False", "None", "Error"], a: 1, e: "An empty string is falsy in Python, so bool('') returns False." },
        { s: "Networking", b: "IP address is how many bits (IPv4)?", o: ["16", "32", "64", "128"], a: 1, e: "IPv4 addresses are 32 bits long, written as four octets (e.g., 192.168.1.1)." },
        { s: "Programming", b: "React uses which pattern for UI?", o: ["MVC", "Component-based", "Procedural", "Event-driven only"], a: 1, e: "React uses a component-based architecture where UI is broken into reusable, independent components." },
        { s: "Database", b: "JOIN operation in SQL combines:", o: ["Columns", "Rows from multiple tables", "Databases", "Indexes"], a: 1, e: "SQL JOIN combines rows from two or more tables based on a related column between them." },
        { s: "Programming", b: "What is a closure in JavaScript?", o: ["A loop structure", "Function with access to outer scope", "Error handler", "DOM element"], a: 1, e: "A closure is a function that retains access to variables from its outer (enclosing) function scope." },
        { s: "Networking", b: "OSI model has how many layers?", o: ["5", "6", "7", "4"], a: 2, e: "The OSI (Open Systems Interconnection) model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
        { s: "Programming", b: "Which data structure uses FIFO?", o: ["Stack", "Queue", "Tree", "Graph"], a: 1, e: "Queue follows First-In-First-Out (FIFO), where the first element added is the first to be removed." },
        { s: "Programming", b: "What does API stand for?", o: ["Application Programming Interface", "Applied Program Integration", "Automated Process Input", "Application Process Interface"], a: 0, e: "API stands for Application Programming Interface, allowing different software to communicate." },
        { s: "Database", b: "NoSQL database example:", o: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], a: 2, e: "MongoDB is a popular NoSQL document database that stores data in flexible JSON-like documents." },
        { s: "Programming", b: "What is Big O notation used for?", o: ["Memory allocation", "Algorithm efficiency", "File management", "Network speed"], a: 1, e: "Big O notation describes the upper bound of an algorithm's time or space complexity." },
        { s: "Networking", b: "TCP is connection-oriented, UDP is:", o: ["Also connection-oriented", "Connectionless", "Stateful", "Encrypted"], a: 1, e: "UDP (User Datagram Protocol) is connectionless, meaning it sends data without establishing a connection first." }
    ],
    diploma: [
        { s: "Engineering", b: "Highest thermal conductivity:", o: ["Steel", "Aluminum", "Copper", "Iron"], a: 2, e: "Copper has one of the highest thermal conductivities among common metals, making it excellent for heat transfer." },
        { s: "Engineering", b: "DC motor converts:", o: ["Mechanical to electrical", "Electrical to mechanical", "Chemical to electrical", "Thermal to mechanical"], a: 1, e: "A DC motor takes direct current (electrical energy) and converts it into rotational movement (mechanical energy)." },
        { s: "Engineering", b: "Pascal is unit of:", o: ["Force", "Pressure", "Energy", "Torque"], a: 1, e: "The Pascal (Pa) is the SI derived unit of pressure, defined as one newton per square meter." },
        { s: "Engineering", b: "Series circuit current:", o: ["Different", "Same", "Zero", "Variable"], a: 1, e: "In a series circuit, there is only one path for electrons to flow, so the current is the same through all components." },
        { s: "Engineering", b: "Transformer principle:", o: ["Magnetic resonance", "Electromagnetic induction", "Electrostatic induction", "Piezoelectric effect"], a: 1, e: "Transformers work on the principle of Faraday's law of electromagnetic induction to step voltage up or down." },
        { s: "Engineering", b: "Electrical power unit:", o: ["Volt", "Ampere", "Watt", "Ohm"], a: 2, e: "The Watt (W) is the SI unit of power, equivalent to one joule per second." },
        { s: "Engineering", b: "IC chips made from:", o: ["Copper", "Iron", "Silicon", "Aluminum"], a: 2, e: "Integrated circuits (ICs) are primarily made from semiconductor materials, with silicon being the most common." },
        { s: "Engineering", b: "CAD stands for:", o: ["Computer Aided Design", "Computer Automated Drawing", "Central Auto Design", "Computer Applied Drafting"], a: 0, e: "CAD (Computer-Aided Design) is software used by architects, engineers, and designers to create precision drawings." },
        { s: "Engineering", b: "Unit of capacitance:", o: ["Farad", "Henry", "Ohm", "Weber"], a: 0, e: "The Farad (F) is the SI unit of electrical capacitance." },
        { s: "Engineering", b: "Kirchhoff's Current Law is based on conservation of:", o: ["Energy", "Charge", "Momentum", "Mass"], a: 1, e: "KCL states that total current entering a junction equals total current leaving, which is conservation of electric charge." },
        { s: "Engineering", b: "Ohm's law formula:", o: ["V = IR", "P = VI", "V = I/R", "R = VI"], a: 0, e: "Ohm's law states V = IR, where V is voltage, I is current, and R is resistance." },
        { s: "Engineering", b: "Fleming's Left Hand Rule is used for:", o: ["Generator", "Motor", "Transformer", "Rectifier"], a: 1, e: "Fleming's Left Hand Rule determines the direction of force on a current-carrying conductor in a magnetic field (motor effect)." },
        { s: "Engineering", b: "Unit of inductance:", o: ["Farad", "Henry", "Ohm", "Tesla"], a: 1, e: "The Henry (H) is the SI unit of electrical inductance." },
        { s: "Engineering", b: "Diode allows current in:", o: ["Both directions", "One direction only", "No direction", "Alternating"], a: 1, e: "A diode is a semiconductor device that allows current to flow in one direction (forward bias) only." },
        { s: "Engineering", b: "Three-phase supply has how many phases?", o: ["1", "2", "3", "4"], a: 2, e: "Three-phase supply uses 3 alternating currents, each separated by 120 degrees phase difference." },
        { s: "Engineering", b: "PPE stands for:", o: ["Personal Protective Equipment", "Power Plant Engineering", "Primary Protection Element", "Portable Power Equipment"], a: 0, e: "PPE stands for Personal Protective Equipment, essential for workplace safety." },
        { s: "Engineering", b: "Bernoulli's theorem is related to:", o: ["Electricity", "Fluid mechanics", "Optics", "Thermodynamics"], a: 1, e: "Bernoulli's theorem relates pressure, velocity, and height for fluid flow in an ideal scenario." },
        { s: "Engineering", b: "Specific gravity has:", o: ["No units", "kg/m³", "N/m²", "Pa"], a: 0, e: "Specific gravity is a ratio of a substance's density to water's density, so it is dimensionless (no units)." },
        { s: "Engineering", b: "Rectifier converts:", o: ["DC to AC", "AC to DC", "AC to AC", "DC to DC"], a: 1, e: "A rectifier is an electrical device that converts alternating current (AC) to direct current (DC)." },
        { s: "Engineering", b: "CNC stands for:", o: ["Computer Numerical Control", "Central Network Computer", "Constant Number Code", "Computer Node Circuit"], a: 0, e: "CNC stands for Computer Numerical Control, used for automated machining operations." },
        { s: "Engineering", b: "Stress is defined as:", o: ["Force per area", "Force per length", "Area per force", "Energy per volume"], a: 0, e: "Stress = Force / Area. It measures the internal resistance of a material to deformation." },
        { s: "Engineering", b: "Young's modulus measures:", o: ["Hardness", "Elasticity", "Viscosity", "Density"], a: 1, e: "Young's modulus (E) measures the stiffness/elasticity of a solid material." },
        { s: "Engineering", b: "Efficiency of a machine is always:", o: ["Greater than 100%", "Equal to 100%", "Less than 100%", "Zero"], a: 2, e: "Due to friction and energy losses, efficiency of a real machine is always less than 100%." },
        { s: "Engineering", b: "LED stands for:", o: ["Light Emitting Diode", "Low Energy Device", "Linear Electronic Driver", "Laser Emission Detector"], a: 0, e: "LED stands for Light Emitting Diode, a semiconductor device that emits light when current flows through it." },
        { s: "Engineering", b: "Mild steel contains carbon percentage:", o: ["0.05–0.25%", "0.5–1.0%", "1.0–2.0%", "2.0–4.0%"], a: 0, e: "Mild steel (low carbon steel) contains approximately 0.05% to 0.25% carbon content." },
        { s: "Engineering", b: "Frequency of AC supply in India:", o: ["60 Hz", "50 Hz", "40 Hz", "100 Hz"], a: 1, e: "India uses 50 Hz frequency for its AC power supply (230V, 50Hz)." },
        { s: "Engineering", b: "Torque is the product of:", o: ["Mass and velocity", "Force and distance", "Pressure and area", "Power and time"], a: 1, e: "Torque = Force × Perpendicular distance from axis of rotation." },
        { s: "Engineering", b: "Galvanization protects iron from:", o: ["Heat", "Corrosion", "Magnetism", "Radiation"], a: 1, e: "Galvanization is coating iron/steel with zinc to prevent rusting (corrosion)." },
        { s: "Engineering", b: "Relay is used for:", o: ["Amplification", "Switching", "Rectification", "Oscillation"], a: 1, e: "A relay is an electrically operated switch used to control a high-power circuit with a low-power signal." },
        { s: "Engineering", b: "Power factor in AC circuits ranges from:", o: ["-1 to 1", "0 to 1", "0 to infinity", "1 to 100"], a: 1, e: "Power factor ranges from 0 to 1 (or 0 to 100%), with 1 being ideal (purely resistive load)." }
    ],
    neet: [
        { s: "Biology", b: "Powerhouse of cell:", o: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"], a: 1, e: "Mitochondria are called powerhouses because they generate most of the cell's supply of ATP (energy)." },
        { s: "Biology", b: "Photosynthesis occurs in:", o: ["Mitochondria", "Nucleus", "Chloroplast", "Ribosome"], a: 2, e: "Chloroplasts contain chlorophyll, which absorbs light energy to drive photosynthesis in plant cells." },
        { s: "Biology", b: "Normal body temp:", o: ["32°C", "37°C", "42°C", "28°C"], a: 1, e: "The normal resting body temperature for a healthy adult is typically around 37°C (98.6°F)." },
        { s: "Chemistry", b: "pH of blood:", o: ["6.4", "7.4", "8.4", "5.4"], a: 1, e: "Human blood is slightly basic (alkaline) with a tightly regulated pH range of 7.35 to 7.45." },
        { s: "Biology", b: "Insulin secreted by:", o: ["Liver", "Kidney", "Pancreas", "Thyroid"], a: 2, e: "Insulin is a hormone produced by the beta cells of the pancreatic islets to regulate blood sugar levels." },
        { s: "Biology", b: "Universal donor blood group:", o: ["A", "B", "AB", "O"], a: 3, e: "Type O negative blood has no A or B antigens, making it safe to donate to anyone." },
        { s: "Biology", b: "Largest human organ:", o: ["Heart", "Liver", "Lungs", "Skin"], a: 3, e: "The skin is the body's largest organ, covering the entire outside of the body." },
        { s: "Chemistry", b: "Sunlight vitamin:", o: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], a: 3, e: "Vitamin D is synthesized in the skin when exposed to sunlight (UVB radiation)." },
        { s: "Biology", b: "Number of bones in human body:", o: ["200", "206", "212", "198"], a: 1, e: "An adult human skeleton consists of 206 bones, though we are born with more that fuse together over time." },
        { s: "Biology", b: "Which gas do plants absorb during photosynthesis?", o: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], a: 2, e: "Plants take in carbon dioxide (CO₂) from the air and use it to produce glucose and oxygen." },
        { s: "Biology", b: "DNA stands for:", o: ["Deoxyribose Nucleic Acid", "Deoxyribonucleic Acid", "Dinitro Amino Acid", "Double Nucleotide Arrangement"], a: 1, e: "DNA stands for Deoxyribonucleic Acid, the molecule carrying genetic instructions." },
        { s: "Biology", b: "Which blood cells fight infection?", o: ["RBC", "WBC", "Platelets", "Plasma"], a: 1, e: "White Blood Cells (WBC/Leukocytes) are part of the immune system and fight infections." },
        { s: "Biology", b: "Mendel is known as father of:", o: ["Taxonomy", "Genetics", "Evolution", "Ecology"], a: 1, e: "Gregor Mendel's work with pea plants established the fundamental laws of inheritance (genetics)." },
        { s: "Chemistry", b: "Atomic number of Carbon:", o: ["4", "6", "8", "12"], a: 1, e: "Carbon has atomic number 6, meaning it has 6 protons in its nucleus." },
        { s: "Biology", b: "Haemoglobin contains which metal?", o: ["Copper", "Iron", "Zinc", "Magnesium"], a: 1, e: "Haemoglobin contains iron (Fe²⁺) in its heme group, which binds oxygen for transport in blood." },
        { s: "Biology", b: "Which hormone controls blood sugar?", o: ["Thyroxine", "Adrenaline", "Insulin", "Estrogen"], a: 2, e: "Insulin is produced by the pancreas and regulates blood glucose levels by promoting glucose uptake." },
        { s: "Chemistry", b: "Molecular formula of glucose:", o: ["C₆H₁₀O₅", "C₆H₁₂O₆", "C₁₂H₂₂O₁₁", "CH₂O"], a: 1, e: "Glucose has the molecular formula C₆H₁₂O₆, a simple monosaccharide sugar." },
        { s: "Biology", b: "Number of chambers in human heart:", o: ["2", "3", "4", "5"], a: 2, e: "The human heart has 4 chambers: 2 atria (upper) and 2 ventricles (lower)." },
        { s: "Biology", b: "Which part of the brain controls balance?", o: ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], a: 1, e: "The cerebellum coordinates voluntary movements, balance, and posture." },
        { s: "Chemistry", b: "Bleaching powder formula:", o: ["CaCl₂", "CaOCl₂", "Ca(OH)₂", "CaCO₃"], a: 1, e: "Bleaching powder (calcium hypochlorite) has the formula CaOCl₂ or Ca(ClO)₂." },
        { s: "Biology", b: "Which vitamin helps in blood clotting?", o: ["Vitamin A", "Vitamin C", "Vitamin E", "Vitamin K"], a: 3, e: "Vitamin K is essential for the synthesis of clotting factors in the liver." },
        { s: "Biology", b: "Largest gland in human body:", o: ["Thyroid", "Pancreas", "Liver", "Pituitary"], a: 2, e: "The liver is the largest gland (and internal organ) in the human body, weighing about 1.5 kg." },
        { s: "Biology", b: "Prokaryotic cell lacks:", o: ["Cell wall", "Cell membrane", "Nuclear membrane", "Ribosome"], a: 2, e: "Prokaryotic cells lack a nuclear membrane (no true nucleus); their DNA is in the nucleoid region." },
        { s: "Chemistry", b: "Ethanol is a:", o: ["Ketone", "Aldehyde", "Alcohol", "Acid"], a: 2, e: "Ethanol (C₂H₅OH) is an alcohol, characterized by the -OH (hydroxyl) functional group." },
        { s: "Biology", b: "Process of cell division for growth:", o: ["Meiosis", "Mitosis", "Budding", "Fission"], a: 1, e: "Mitosis is the type of cell division used for growth and repair, producing two identical daughter cells." },
        { s: "Biology", b: "Dialysis is related to which organ?", o: ["Heart", "Liver", "Kidney", "Lungs"], a: 2, e: "Dialysis is an artificial process that performs the kidney's function of filtering waste from blood." },
        { s: "Biology", b: "Malaria is caused by:", o: ["Virus", "Bacteria", "Protozoa", "Fungi"], a: 2, e: "Malaria is caused by Plasmodium, a protozoan parasite transmitted by female Anopheles mosquitoes." },
        { s: "Chemistry", b: "Which acid is present in vinegar?", o: ["Citric acid", "Acetic acid", "Formic acid", "Lactic acid"], a: 1, e: "Vinegar contains acetic acid (CH₃COOH), typically at 4-8% concentration." },
        { s: "Biology", b: "Which tissue connects muscle to bone?", o: ["Ligament", "Tendon", "Cartilage", "Nerve"], a: 1, e: "Tendons are strong connective tissues that attach muscles to bones, enabling movement." },
        { s: "Biology", b: "Oxygen in atmosphere is maintained by:", o: ["Respiration", "Photosynthesis", "Decomposition", "Combustion"], a: 1, e: "Photosynthesis by plants and algae produces oxygen, maintaining atmospheric oxygen levels." }
    ],
    appsc: [
        { s: "General Knowledge", b: "Capital of AP:", o: ["Hyderabad", "Visakhapatnam", "Amaravati", "Tirupati"], a: 2, e: "Amaravati is the designated legislative capital of the Indian state of Andhra Pradesh." },
        { s: "History", b: "AP bifurcation year:", o: ["2012", "2013", "2014", "2015"], a: 2, e: "The Andhra Pradesh Reorganisation Act, 2014 bifurcated the state into Telangana and residuary Andhra Pradesh." },
        { s: "General Knowledge", b: "National bird of India:", o: ["Sparrow", "Peacock", "Parrot", "Eagle"], a: 1, e: "The Indian peacock (Pavo cristatus) was declared the National Bird of India in 1963." },
        { s: "Maths", b: "15% of number is 75, number is:", o: ["500", "450", "600", "550"], a: 0, e: "Let x be the number. 0.15 * x = 75. Therefore x = 75 / 0.15 = 500." },
        { s: "Maths", b: "Train 360km in 4hrs, speed:", o: ["90 km/h", "80 km/h", "100 km/h", "85 km/h"], a: 0, e: "Speed = Distance / Time. So, 360 km / 4 hours = 90 km/h." },
        { s: "History", b: "India independence year:", o: ["1945", "1946", "1947", "1948"], a: 2, e: "India gained independence from British rule on August 15, 1947." },
        { s: "Reasoning", b: "Series: 2, 4, 8, 16, ___", o: ["18", "32", "24", "20"], a: 1, e: "This is a geometric progression where each term is multiplied by 2 (16 * 2 = 32)." },
        { s: "General Knowledge", b: "Currency of Japan:", o: ["Yuan", "Won", "Yen", "Rupee"], a: 2, e: "The Japanese Yen (¥) is the official currency of Japan." },
        { s: "Indian Polity", b: "Who is the first citizen of India?", o: ["Prime Minister", "Chief Justice", "President", "Vice President"], a: 2, e: "The President of India is the head of state and the first citizen of India." },
        { s: "General Knowledge", b: "Longest river in India:", o: ["Brahmaputra", "Godavari", "Ganga", "Yamuna"], a: 2, e: "The Ganga (Ganges) is the longest river flowing entirely within the borders of India." },
        { s: "Indian Polity", b: "Total articles in Indian Constitution originally:", o: ["295", "395", "448", "350"], a: 1, e: "The original Indian Constitution had 395 articles. It has since been amended many times." },
        { s: "History", b: "Who wrote Arthashastra?", o: ["Valmiki", "Kautilya", "Kalidasa", "Tulsidas"], a: 1, e: "Arthashastra was written by Kautilya (Chanakya), an ancient Indian philosopher and advisor to Chandragupta Maurya." },
        { s: "General Knowledge", b: "National flower of India:", o: ["Rose", "Sunflower", "Lotus", "Jasmine"], a: 2, e: "The Lotus (Nelumbo nucifera) is the National Flower of India, symbolizing purity and beauty." },
        { s: "Maths", b: "Simple interest on Rs.5000 at 10% for 2 years:", o: ["500", "1000", "1500", "2000"], a: 1, e: "SI = P×R×T/100 = 5000×10×2/100 = Rs.1000" },
        { s: "Reasoning", b: "Odd one out: 2, 5, 10, 17, 28, 37", o: ["10", "17", "28", "37"], a: 3, e: "Pattern: differences are 3,5,7,11,9. Should be 3,5,7,9,11. So 28 should be 26, making 37 the odd one." },
        { s: "General Knowledge", b: "Which planet is known as Red Planet?", o: ["Venus", "Mars", "Jupiter", "Saturn"], a: 1, e: "Mars is called the Red Planet because iron oxide (rust) on its surface gives it a reddish appearance." },
        { s: "History", b: "First battle of Panipat year:", o: ["1526", "1556", "1761", "1576"], a: 0, e: "The First Battle of Panipat was fought in 1526 between Babur and Ibrahim Lodi." },
        { s: "Indian Polity", b: "Minimum age to become PM of India:", o: ["21", "25", "30", "35"], a: 1, e: "To become PM, one must be a member of Lok Sabha (min 25 years) or Rajya Sabha (min 30 years). Effective minimum is 25." },
        { s: "Maths", b: "Average of 10, 20, 30, 40, 50:", o: ["25", "30", "35", "40"], a: 1, e: "Average = (10+20+30+40+50)/5 = 150/5 = 30" },
        { s: "General Knowledge", b: "Which state is known as 'Rice Bowl of India'?", o: ["Punjab", "Andhra Pradesh", "Tamil Nadu", "West Bengal"], a: 1, e: "Andhra Pradesh is known as the 'Rice Bowl of India' due to its extensive rice cultivation." },
        { s: "History", b: "Quit India Movement started in:", o: ["1940", "1942", "1944", "1946"], a: 1, e: "The Quit India Movement was launched on August 8, 1942, by Mahatma Gandhi demanding an end to British rule." },
        { s: "Indian Polity", b: "How many Lok Sabha seats does AP have?", o: ["25", "28", "42", "17"], a: 0, e: "Andhra Pradesh has 25 Lok Sabha seats after bifurcation in 2014." },
        { s: "Reasoning", b: "If APPLE = 50, then MANGO = ?", o: ["55", "57", "59", "51"], a: 0, e: "A=1,P=16,P=16,L=12,E=5 → 50. M=13,A=1,N=14,G=7,O=15 → 50. But using A=1 scheme: 13+1+14+7+15=50." },
        { s: "General Knowledge", b: "National animal of India:", o: ["Lion", "Elephant", "Bengal Tiger", "Leopard"], a: 2, e: "The Bengal Tiger (Panthera tigris tigris) is the National Animal of India." },
        { s: "History", b: "Who founded Arya Samaj?", o: ["Raja Ram Mohan Roy", "Swami Vivekananda", "Swami Dayanand Saraswati", "Annie Besant"], a: 2, e: "Swami Dayanand Saraswati founded Arya Samaj in 1875 in Bombay." },
        { s: "Maths", b: "Profit % if CP=200, SP=250:", o: ["20%", "25%", "30%", "50%"], a: 1, e: "Profit = SP - CP = 50. Profit% = (50/200)×100 = 25%" },
        { s: "General Knowledge", b: "Largest continent:", o: ["Africa", "North America", "Asia", "Europe"], a: 2, e: "Asia is the largest continent by both area and population." },
        { s: "Indian Polity", b: "Right to Education is a:", o: ["Fundamental Right", "Directive Principle", "Legal Right", "Natural Right"], a: 0, e: "Right to Education was added as a Fundamental Right under Article 21-A by the 86th Amendment (2002)." },
        { s: "Reasoning", b: "Clock shows 3:15, angle between hands:", o: ["0°", "7.5°", "15°", "22.5°"], a: 1, e: "At 3:15, hour hand moves 7.5° past the 3 mark. Minute hand at 3 (90°). Angle = 97.5° - 90° = 7.5°." },
        { s: "General Knowledge", b: "Tirupati temple is dedicated to:", o: ["Lord Shiva", "Lord Venkateswara", "Lord Krishna", "Lord Rama"], a: 1, e: "The famous Tirupati Balaji temple (Tirumala) is dedicated to Lord Venkateswara (a form of Lord Vishnu)." }
    ]
};
