export const IV_QUESTION_POOL = [
    "Tell me about yourself and your background.",
    "Why do you want this role?",
    "What are your greatest strengths?",
    "What is your biggest weakness?",
    "Describe a challenging situation you faced.",
    "Where do you see yourself in 5 years?",
    "Tell me about a project you are most proud of.",
    "How do you handle pressure or tight deadlines?",
    "Describe your teamwork experience.",
    "What motivates you to work hard?",
    "Tell me about a time you failed and what you learned.",
    "How do you prioritize tasks?",
    "What do you know about our company?",
    "Why should we hire you?",
    "What are your salary expectations?",
    "Explain a complex technical concept to a non-technical person.",
    "How do you stay updated with the latest industry trends?",
    "Describe a difficult decision you had to make.",
    "What is your ideal work environment?",
    "How do you handle negative feedback or criticism?",
    "Tell me about a time you had a conflict with a coworker.",
    "What is your biggest professional achievement?",
    "How would your previous manager describe you?",
    "Can you describe a time when you went above and beyond?",
    "Tell me about a time you had to adapt to a sudden change.",
    "How do you measure your own success?",
    "Describe a situation where you had to persuade someone.",
    "Tell me about your leadership experience, even informal.",
    "How do you handle multiple important projects simultaneously?",
    "What do you like to do outside of work?",
    "Describe a time you solved a problem innovatively.",
    "Tell me about a time you had to learn something new quickly.",
    "What frustrates you in a workplace?",
    "What are you looking for in your next role?",
    "Do you have any questions for us?"
];
export const FILLERS = ['um', 'uh', 'like', 'you know', 'basically', 'literally', 'actually', 'so', 'right', 'okay'];
export const DIFF_T = { easy: 90, medium: 60, hard: 45 };
export const DIFF_Q = { easy: 10, medium: 20, hard: 30 };
