const DETAIL_DEFS = {
    frontend: {
        title: 'Frontend Developer', sub: 'Step by step guide to becoming a modern frontend developer',
        nodes: [
            { section: 'Internet Basics' },
            { row: [{ id: 'f-internet', label: 'How the Internet Works', type: 'req' }, { id: 'f-http', label: 'HTTP / HTTPS', type: 'req' }, { id: 'f-dns', label: 'DNS & Domain Names', type: 'req' }] },
            { section: 'HTML' },
            { row: [{ id: 'f-html', label: 'Semantic HTML', type: 'req' }, { id: 'f-forms', label: 'Forms & Validation', type: 'req' }, { id: 'f-a11y', label: 'Accessibility Basics', type: 'req' }] },
            { section: 'CSS' },
            { row: [{ id: 'f-css', label: 'CSS Fundamentals', type: 'req' }, { id: 'f-flex', label: 'Flexbox', type: 'req' }, { id: 'f-grid', label: 'CSS Grid', type: 'req' }] },
            { row: [{ id: 'f-responsive', label: 'Responsive Design', type: 'req' }, { id: 'f-animations', label: 'CSS Animations', type: 'opt' }, { id: 'f-sass', label: 'SASS / PostCSS', type: 'opt' }] },
            { section: 'JavaScript' },
            { row: [{ id: 'f-jsbasics', label: 'JS Fundamentals', type: 'req' }, { id: 'f-dom', label: 'DOM Manipulation', type: 'req' }, { id: 'f-es6', label: 'ES6+ Features', type: 'req' }] },
            { row: [{ id: 'f-async', label: 'Async JS (Promises, Async/Await)', type: 'req' }, { id: 'f-fetch', label: 'Fetch API & AJAX', type: 'req' }] },
            { section: 'Version Control' },
            { row: [{ id: 'f-git', label: 'Git Basics', type: 'req' }, { id: 'f-github', label: 'GitHub / GitLab', type: 'req' }] },
            { section: 'Package Managers' },
            { row: [{ id: 'f-npm', label: 'npm / yarn / pnpm', type: 'req' }] },
            { section: 'Framework (Pick One)' },
            { row: [{ id: 'f-react', label: 'React.js', type: 'req' }, { id: 'f-vue', label: 'Vue.js', type: 'opt' }, { id: 'f-angular', label: 'Angular', type: 'opt' }] },
            { section: 'State Management' },
            { row: [{ id: 'f-state', label: 'React Context / Zustand', type: 'req' }, { id: 'f-redux', label: 'Redux', type: 'opt' }] },
            { section: 'CSS Framework' },
            { row: [{ id: 'f-tailwind', label: 'Tailwind CSS', type: 'req' }, { id: 'f-mui', label: 'Material UI / shadcn', type: 'opt' }] },
            { section: 'Build Tools' },
            { row: [{ id: 'f-vite', label: 'Vite', type: 'req' }, { id: 'f-webpack', label: 'Webpack', type: 'opt' }] },
            { section: 'SSR / SSG' },
            { row: [{ id: 'f-nextjs', label: 'Next.js', type: 'req' }, { id: 'f-ts', label: 'TypeScript', type: 'req' }] },
            { section: 'Testing' },
            { row: [{ id: 'f-jest', label: 'Jest / Vitest', type: 'req' }, { id: 'f-cypress', label: 'Cypress / Playwright', type: 'opt' }] },
            { section: 'Performance & SEO' },
            { row: [{ id: 'f-perf', label: 'Web Performance', type: 'req' }, { id: 'f-seo', label: 'SEO Basics', type: 'req' }, { id: 'f-pwa', label: 'PWA', type: 'opt' }] },
        ]
    },
    backend: {
        title: 'Backend Developer', sub: 'Step by step guide to becoming a backend developer',
        nodes: [
            { section: 'Internet & OS' },
            { row: [{ id: 'b-http', label: 'HTTP / HTTPS / APIs', type: 'req' }, { id: 'b-terminal', label: 'Terminal / Shell', type: 'req' }, { id: 'b-os', label: 'OS Fundamentals', type: 'req' }] },
            { section: 'Programming Language' },
            { row: [{ id: 'b-python', label: 'Python', type: 'req' }, { id: 'b-nodejs', label: 'Node.js', type: 'opt' }, { id: 'b-java', label: 'Java', type: 'opt' }, { id: 'b-go', label: 'Go', type: 'opt' }] },
            { section: 'Version Control' },
            { row: [{ id: 'b-git', label: 'Git & GitHub', type: 'req' }] },
            { section: 'Databases' },
            { row: [{ id: 'b-sql', label: 'PostgreSQL / MySQL', type: 'req' }, { id: 'b-nosql', label: 'MongoDB', type: 'opt' }, { id: 'b-redis', label: 'Redis', type: 'opt' }] },
            { section: 'API Design' },
            { row: [{ id: 'b-rest', label: 'REST API Design', type: 'req' }, { id: 'b-graphql', label: 'GraphQL', type: 'opt' }, { id: 'b-auth', label: 'Authentication (JWT, OAuth)', type: 'req' }] },
            { section: 'ORM' },
            { row: [{ id: 'b-orm', label: 'Prisma / SQLAlchemy / Sequelize', type: 'req' }] },
            { section: 'Caching & Message Queues' },
            { row: [{ id: 'b-cache', label: 'Caching Strategies', type: 'req' }, { id: 'b-mq', label: 'RabbitMQ / Kafka', type: 'opt' }] },
            { section: 'Testing' },
            { row: [{ id: 'b-test', label: 'Unit & Integration Testing', type: 'req' }, { id: 'b-ci', label: 'CI/CD (GitHub Actions)', type: 'req' }] },
            { section: 'Containerization' },
            { row: [{ id: 'b-docker', label: 'Docker', type: 'req' }, { id: 'b-k8s', label: 'Kubernetes', type: 'opt' }] },
            { section: 'Cloud & Deployment' },
            { row: [{ id: 'b-aws', label: 'AWS / GCP / Azure', type: 'req' }, { id: 'b-nginx', label: 'Nginx / Reverse Proxy', type: 'req' }] },
            { section: 'Architecture' },
            { row: [{ id: 'b-micro', label: 'Microservices', type: 'opt' }, { id: 'b-patterns', label: 'Design Patterns', type: 'req' }, { id: 'b-scaling', label: 'Scaling & Load Balancing', type: 'opt' }] },
        ]
    },
    react: {
        title: 'React Developer', sub: 'Complete React developer roadmap from basics to advanced',
        nodes: [
            { section: 'Prerequisites' },
            { row: [{ id: 'r-html', label: 'HTML & CSS', type: 'req' }, { id: 'r-js', label: 'JavaScript (ES6+)', type: 'req' }, { id: 'r-git', label: 'Git Basics', type: 'req' }] },
            { section: 'React Fundamentals' },
            { row: [{ id: 'r-jsx', label: 'JSX & Components', type: 'req' }, { id: 'r-props', label: 'Props & State', type: 'req' }, { id: 'r-events', label: 'Event Handling', type: 'req' }] },
            { row: [{ id: 'r-lists', label: 'Lists & Keys', type: 'req' }, { id: 'r-forms', label: 'Controlled Forms', type: 'req' }, { id: 'r-lifecycle', label: 'Component Lifecycle', type: 'req' }] },
            { section: 'Hooks' },
            { row: [{ id: 'r-usestate', label: 'useState & useEffect', type: 'req' }, { id: 'r-useref', label: 'useRef & useMemo', type: 'req' }, { id: 'r-usecb', label: 'useCallback', type: 'req' }] },
            { row: [{ id: 'r-context', label: 'useContext', type: 'req' }, { id: 'r-reducer', label: 'useReducer', type: 'req' }, { id: 'r-custom', label: 'Custom Hooks', type: 'req' }] },
            { section: 'Routing' },
            { row: [{ id: 'r-router', label: 'React Router v6', type: 'req' }, { id: 'r-layouts', label: 'Nested Routes & Layouts', type: 'req' }] },
            { section: 'State Management' },
            { row: [{ id: 'r-zustand', label: 'Zustand', type: 'req' }, { id: 'r-redux', label: 'Redux Toolkit', type: 'opt' }, { id: 'r-tanstack', label: 'TanStack Query', type: 'req' }] },
            { section: 'Styling' },
            { row: [{ id: 'r-css', label: 'CSS Modules', type: 'req' }, { id: 'r-tailwind', label: 'Tailwind CSS', type: 'req' }, { id: 'r-styled', label: 'Styled Components', type: 'opt' }] },
            { section: 'API & Data Fetching' },
            { row: [{ id: 'r-fetch', label: 'Fetch / Axios', type: 'req' }, { id: 'r-swr', label: 'SWR / React Query', type: 'req' }, { id: 'r-graphql', label: 'GraphQL + Apollo', type: 'opt' }] },
            { section: 'Testing' },
            { row: [{ id: 'r-jest', label: 'Jest + RTL', type: 'req' }, { id: 'r-e2e', label: 'Cypress / Playwright', type: 'opt' }] },
            { section: 'Frameworks & SSR' },
            { row: [{ id: 'r-nextjs', label: 'Next.js (App Router)', type: 'req' }, { id: 'r-remix', label: 'Remix', type: 'opt' }] },
            { section: 'Advanced' },
            { row: [{ id: 'r-ts', label: 'TypeScript', type: 'req' }, { id: 'r-perf', label: 'Performance Optimization', type: 'req' }, { id: 'r-a11y', label: 'Accessibility', type: 'req' }] },
        ]
    },
    javascript: {
        title: 'JavaScript', sub: 'Master JavaScript from fundamentals to advanced concepts',
        nodes: [
            { section: 'Basics' },
            { row: [{ id: 'js-vars', label: 'Variables & Data Types', type: 'req' }, { id: 'js-ops', label: 'Operators & Expressions', type: 'req' }, { id: 'js-flow', label: 'Control Flow (if/switch)', type: 'req' }] },
            { section: 'Functions & Scope' },
            { row: [{ id: 'js-func', label: 'Functions & Arrow Functions', type: 'req' }, { id: 'js-scope', label: 'Scope & Closures', type: 'req' }, { id: 'js-hoisting', label: 'Hoisting & TDZ', type: 'req' }] },
            { section: 'Data Structures' },
            { row: [{ id: 'js-arr', label: 'Arrays & Methods', type: 'req' }, { id: 'js-obj', label: 'Objects & Destructuring', type: 'req' }, { id: 'js-map', label: 'Map, Set, WeakMap', type: 'req' }] },
            { section: 'DOM & Events' },
            { row: [{ id: 'js-dom', label: 'DOM Manipulation', type: 'req' }, { id: 'js-events', label: 'Event Listeners & Bubbling', type: 'req' }, { id: 'js-storage', label: 'LocalStorage & SessionStorage', type: 'req' }] },
            { section: 'Asynchronous JS' },
            { row: [{ id: 'js-cb', label: 'Callbacks & Event Loop', type: 'req' }, { id: 'js-promise', label: 'Promises', type: 'req' }, { id: 'js-async', label: 'Async / Await', type: 'req' }] },
            { section: 'ES6+ Features' },
            { row: [{ id: 'js-template', label: 'Template Literals', type: 'req' }, { id: 'js-spread', label: 'Spread / Rest Operator', type: 'req' }, { id: 'js-modules', label: 'ES Modules (import/export)', type: 'req' }] },
            { section: 'OOP' },
            { row: [{ id: 'js-class', label: 'Classes & Prototypes', type: 'req' }, { id: 'js-this', label: 'this Keyword', type: 'req' }, { id: 'js-inherit', label: 'Inheritance', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'js-regex', label: 'Regular Expressions', type: 'opt' }, { id: 'js-error', label: 'Error Handling', type: 'req' }, { id: 'js-proxy', label: 'Proxy & Reflect', type: 'opt' }] },
            { row: [{ id: 'js-perf', label: 'Performance & Memory', type: 'opt' }, { id: 'js-ts', label: 'TypeScript', type: 'req' }] },
        ]
    },
    python: {
        title: 'Python', sub: 'Learn Python from zero to advanced for jobs and projects',
        nodes: [
            { section: 'Basics' },
            { row: [{ id: 'py-syntax', label: 'Syntax & Variables', type: 'req' }, { id: 'py-types', label: 'Data Types & Operators', type: 'req' }, { id: 'py-flow', label: 'Control Flow', type: 'req' }] },
            { section: 'Functions & Modules' },
            { row: [{ id: 'py-func', label: 'Functions & Lambda', type: 'req' }, { id: 'py-module', label: 'Modules & Packages', type: 'req' }, { id: 'py-error', label: 'Error Handling', type: 'req' }] },
            { section: 'Data Structures' },
            { row: [{ id: 'py-list', label: 'Lists & Tuples', type: 'req' }, { id: 'py-dict', label: 'Dictionaries & Sets', type: 'req' }, { id: 'py-comp', label: 'List Comprehensions', type: 'req' }] },
            { section: 'OOP' },
            { row: [{ id: 'py-class', label: 'Classes & Objects', type: 'req' }, { id: 'py-inherit', label: 'Inheritance & Polymorphism', type: 'req' }, { id: 'py-deco', label: 'Decorators & Generators', type: 'req' }] },
            { section: 'File & Database' },
            { row: [{ id: 'py-file', label: 'File I/O', type: 'req' }, { id: 'py-json', label: 'JSON & CSV', type: 'req' }, { id: 'py-sql', label: 'SQLite / PostgreSQL', type: 'req' }] },
            { section: 'Libraries' },
            { row: [{ id: 'py-numpy', label: 'NumPy & Pandas', type: 'req' }, { id: 'py-flask', label: 'Flask / FastAPI', type: 'req' }, { id: 'py-requests', label: 'Requests / APIs', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'py-venv', label: 'Virtual Environments', type: 'req' }, { id: 'py-test', label: 'Testing (pytest)', type: 'req' }, { id: 'py-async', label: 'AsyncIO', type: 'opt' }] },
            { row: [{ id: 'py-ml', label: 'Machine Learning (scikit-learn)', type: 'opt' }, { id: 'py-django', label: 'Django', type: 'opt' }] },
        ]
    },
    devops: {
        title: 'DevOps Engineer', sub: 'Complete DevOps roadmap from fundamentals to production',
        nodes: [
            { section: 'Fundamentals' },
            { row: [{ id: 'do-linux', label: 'Linux & Terminal', type: 'req' }, { id: 'do-network', label: 'Networking Basics', type: 'req' }, { id: 'do-scripting', label: 'Bash / Python Scripting', type: 'req' }] },
            { section: 'Version Control' },
            { row: [{ id: 'do-git', label: 'Git & Branching Strategies', type: 'req' }, { id: 'do-github', label: 'GitHub Actions / GitLab CI', type: 'req' }] },
            { section: 'Containers' },
            { row: [{ id: 'do-docker', label: 'Docker', type: 'req' }, { id: 'do-compose', label: 'Docker Compose', type: 'req' }, { id: 'do-registry', label: 'Container Registries', type: 'req' }] },
            { section: 'CI/CD' },
            { row: [{ id: 'do-ci', label: 'CI/CD Pipelines', type: 'req' }, { id: 'do-jenkins', label: 'Jenkins', type: 'opt' }, { id: 'do-argocd', label: 'ArgoCD', type: 'opt' }] },
            { section: 'Orchestration' },
            { row: [{ id: 'do-k8s', label: 'Kubernetes', type: 'req' }, { id: 'do-helm', label: 'Helm Charts', type: 'req' }] },
            { section: 'Infrastructure as Code' },
            { row: [{ id: 'do-terraform', label: 'Terraform', type: 'req' }, { id: 'do-ansible', label: 'Ansible', type: 'opt' }, { id: 'do-pulumi', label: 'Pulumi', type: 'opt' }] },
            { section: 'Cloud Providers' },
            { row: [{ id: 'do-aws', label: 'AWS (EC2, S3, Lambda)', type: 'req' }, { id: 'do-gcp', label: 'GCP', type: 'opt' }, { id: 'do-azure', label: 'Azure', type: 'opt' }] },
            { section: 'Monitoring & Logging' },
            { row: [{ id: 'do-prom', label: 'Prometheus & Grafana', type: 'req' }, { id: 'do-elk', label: 'ELK Stack', type: 'opt' }, { id: 'do-datadog', label: 'Datadog', type: 'opt' }] },
            { section: 'Security' },
            { row: [{ id: 'do-sec', label: 'DevSecOps Basics', type: 'req' }, { id: 'do-vault', label: 'HashiCorp Vault', type: 'opt' }] },
        ]
    },
    docker: {
        title: 'Docker', sub: 'Master Docker containers from basics to production',
        nodes: [
            { section: 'Fundamentals' },
            { row: [{ id: 'dk-what', label: 'What is Docker?', type: 'req' }, { id: 'dk-install', label: 'Install & Setup', type: 'req' }, { id: 'dk-vs', label: 'VM vs Containers', type: 'req' }] },
            { section: 'Core Concepts' },
            { row: [{ id: 'dk-image', label: 'Images & Layers', type: 'req' }, { id: 'dk-container', label: 'Containers', type: 'req' }, { id: 'dk-dockerfile', label: 'Dockerfile', type: 'req' }] },
            { section: 'Working with Docker' },
            { row: [{ id: 'dk-cmd', label: 'Docker CLI Commands', type: 'req' }, { id: 'dk-volume', label: 'Volumes & Bind Mounts', type: 'req' }, { id: 'dk-network', label: 'Networking', type: 'req' }] },
            { section: 'Docker Compose' },
            { row: [{ id: 'dk-compose', label: 'docker-compose.yml', type: 'req' }, { id: 'dk-multi', label: 'Multi-Container Apps', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'dk-multi-stage', label: 'Multi-stage Builds', type: 'req' }, { id: 'dk-registry', label: 'Docker Hub / ECR', type: 'req' }, { id: 'dk-security', label: 'Security Best Practices', type: 'req' }] },
            { row: [{ id: 'dk-swarm', label: 'Docker Swarm', type: 'opt' }, { id: 'dk-k8s', label: 'Docker + Kubernetes', type: 'opt' }] },
        ]
    },
    git: {
        title: 'Git & GitHub', sub: 'Version control from first commit to team collaboration',
        nodes: [
            { section: 'Getting Started' },
            { row: [{ id: 'g-install', label: 'Install Git', type: 'req' }, { id: 'g-config', label: 'git config & SSH', type: 'req' }, { id: 'g-init', label: 'git init & clone', type: 'req' }] },
            { section: 'Basic Commands' },
            { row: [{ id: 'g-add', label: 'add, commit, push', type: 'req' }, { id: 'g-status', label: 'status, log, diff', type: 'req' }, { id: 'g-ignore', label: '.gitignore', type: 'req' }] },
            { section: 'Branching' },
            { row: [{ id: 'g-branch', label: 'Creating Branches', type: 'req' }, { id: 'g-merge', label: 'Merge & Conflicts', type: 'req' }, { id: 'g-rebase', label: 'Rebase', type: 'req' }] },
            { section: 'GitHub' },
            { row: [{ id: 'g-repo', label: 'Repositories & README', type: 'req' }, { id: 'g-pr', label: 'Pull Requests', type: 'req' }, { id: 'g-issues', label: 'Issues & Projects', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'g-stash', label: 'Stash & Cherry-pick', type: 'req' }, { id: 'g-reset', label: 'Reset & Revert', type: 'req' }, { id: 'g-flow', label: 'Git Flow / Trunk-based', type: 'opt' }] },
            { row: [{ id: 'g-actions', label: 'GitHub Actions CI/CD', type: 'req' }, { id: 'g-pages', label: 'GitHub Pages', type: 'opt' }] },
        ]
    },
    sql: {
        title: 'SQL & Databases', sub: 'Master SQL from SELECT to database design',
        nodes: [
            { section: 'Basics' },
            { row: [{ id: 'sq-what', label: 'What is SQL & RDBMS', type: 'req' }, { id: 'sq-select', label: 'SELECT & WHERE', type: 'req' }, { id: 'sq-insert', label: 'INSERT, UPDATE, DELETE', type: 'req' }] },
            { section: 'Filtering & Sorting' },
            { row: [{ id: 'sq-order', label: 'ORDER BY & LIMIT', type: 'req' }, { id: 'sq-like', label: 'LIKE & Wildcards', type: 'req' }, { id: 'sq-in', label: 'IN, BETWEEN, NULL', type: 'req' }] },
            { section: 'Joins' },
            { row: [{ id: 'sq-inner', label: 'INNER JOIN', type: 'req' }, { id: 'sq-left', label: 'LEFT / RIGHT JOIN', type: 'req' }, { id: 'sq-cross', label: 'FULL OUTER & CROSS JOIN', type: 'req' }] },
            { section: 'Aggregation' },
            { row: [{ id: 'sq-group', label: 'GROUP BY', type: 'req' }, { id: 'sq-having', label: 'HAVING & COUNT', type: 'req' }, { id: 'sq-agg', label: 'SUM, AVG, MIN, MAX', type: 'req' }] },
            { section: 'Subqueries & Views' },
            { row: [{ id: 'sq-sub', label: 'Subqueries', type: 'req' }, { id: 'sq-views', label: 'Views', type: 'req' }, { id: 'sq-cte', label: 'CTEs (WITH clause)', type: 'req' }] },
            { section: 'Database Design' },
            { row: [{ id: 'sq-normal', label: 'Normalization (1NF-3NF)', type: 'req' }, { id: 'sq-er', label: 'ER Diagrams', type: 'req' }, { id: 'sq-index', label: 'Indexes & Optimization', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'sq-stored', label: 'Stored Procedures', type: 'opt' }, { id: 'sq-trigger', label: 'Triggers', type: 'opt' }, { id: 'sq-trans', label: 'Transactions & ACID', type: 'req' }] },
        ]
    },
    fullstack: {
        title: 'Full Stack Developer', sub: 'Frontend + Backend + Database = Full Stack',
        nodes: [
            { section: 'Frontend Fundamentals' },
            { row: [{ id: 'fs-html', label: 'HTML & CSS', type: 'req' }, { id: 'fs-js', label: 'JavaScript', type: 'req' }, { id: 'fs-responsive', label: 'Responsive Design', type: 'req' }] },
            { section: 'Frontend Framework' },
            { row: [{ id: 'fs-react', label: 'React.js', type: 'req' }, { id: 'fs-tailwind', label: 'Tailwind CSS', type: 'req' }, { id: 'fs-nextjs', label: 'Next.js', type: 'req' }] },
            { section: 'Backend' },
            { row: [{ id: 'fs-node', label: 'Node.js & Express', type: 'req' }, { id: 'fs-rest', label: 'REST API Design', type: 'req' }, { id: 'fs-auth', label: 'Authentication (JWT)', type: 'req' }] },
            { section: 'Database' },
            { row: [{ id: 'fs-sql', label: 'PostgreSQL', type: 'req' }, { id: 'fs-mongo', label: 'MongoDB', type: 'opt' }, { id: 'fs-orm', label: 'Prisma / Mongoose', type: 'req' }] },
            { section: 'DevOps & Deploy' },
            { row: [{ id: 'fs-git', label: 'Git & GitHub', type: 'req' }, { id: 'fs-docker', label: 'Docker', type: 'req' }, { id: 'fs-deploy', label: 'Vercel / AWS', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'fs-ts', label: 'TypeScript', type: 'req' }, { id: 'fs-test', label: 'Testing', type: 'req' }, { id: 'fs-cicd', label: 'CI/CD Pipeline', type: 'req' }] },
        ]
    },
    aiengineer: {
        title: 'AI Engineer', sub: 'From Python basics to building AI/ML applications',
        nodes: [
            { section: 'Programming Foundation' },
            { row: [{ id: 'ai-python', label: 'Python', type: 'req' }, { id: 'ai-numpy', label: 'NumPy & Pandas', type: 'req' }, { id: 'ai-math', label: 'Linear Algebra & Stats', type: 'req' }] },
            { section: 'Data Science' },
            { row: [{ id: 'ai-viz', label: 'Data Visualization (Matplotlib)', type: 'req' }, { id: 'ai-eda', label: 'EDA & Feature Engineering', type: 'req' }] },
            { section: 'Machine Learning' },
            { row: [{ id: 'ai-sklearn', label: 'scikit-learn', type: 'req' }, { id: 'ai-supervised', label: 'Supervised Learning', type: 'req' }, { id: 'ai-unsupervised', label: 'Unsupervised Learning', type: 'req' }] },
            { section: 'Deep Learning' },
            { row: [{ id: 'ai-nn', label: 'Neural Networks', type: 'req' }, { id: 'ai-pytorch', label: 'PyTorch / TensorFlow', type: 'req' }, { id: 'ai-cnn', label: 'CNNs & RNNs', type: 'req' }] },
            { section: 'NLP & LLMs' },
            { row: [{ id: 'ai-nlp', label: 'NLP Basics', type: 'req' }, { id: 'ai-transformer', label: 'Transformers & Attention', type: 'req' }, { id: 'ai-llm', label: 'LLMs & Prompt Engineering', type: 'req' }] },
            { section: 'MLOps & Deployment' },
            { row: [{ id: 'ai-mlops', label: 'MLflow / W&B', type: 'req' }, { id: 'ai-api', label: 'Model APIs (FastAPI)', type: 'req' }, { id: 'ai-docker', label: 'Docker + Cloud Deploy', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'ai-rag', label: 'RAG & Vector DBs', type: 'req' }, { id: 'ai-agents', label: 'AI Agents', type: 'opt' }, { id: 'ai-finetune', label: 'Fine-tuning LLMs', type: 'opt' }] },
        ]
    },
    android: {
        title: 'Android Developer', sub: 'Learn Android App Development from basics to advanced',
        nodes: [
            { section: 'Programming Language' },
            { row: [{ id: 'a-kotlin', label: 'Kotlin (Recommended)', type: 'req' }, { id: 'a-java', label: 'Java', type: 'opt' }] },
            { section: 'Android Basics' },
            { row: [{ id: 'a-studio', label: 'Android Studio & Gradle', type: 'req' }, { id: 'a-components', label: 'Activities & Fragments', type: 'req' }, { id: 'a-lifecycle', label: 'Component Lifecycle', type: 'req' }] },
            { section: 'UI Design' },
            { row: [{ id: 'a-xml', label: 'XML Layouts', type: 'req' }, { id: 'a-compose', label: 'Jetpack Compose', type: 'req' }, { id: 'a-material', label: 'Material Design', type: 'req' }] },
            { section: 'Data & Networking' },
            { row: [{ id: 'a-retro', label: 'Retrofit & REST APIs', type: 'req' }, { id: 'a-room', label: 'Room Database (SQLite)', type: 'req' }, { id: 'a-prefs', label: 'SharedPreferences / DataStore', type: 'req' }] },
            { section: 'Architecture' },
            { row: [{ id: 'a-mvvm', label: 'MVVM Architecture', type: 'req' }, { id: 'a-coroutines', label: 'Coroutines & Flow', type: 'req' }, { id: 'a-hilt', label: 'Dagger / Hilt (DI)', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'a-services', label: 'Services & WorkManager', type: 'req' }, { id: 'a-firebase', label: 'Firebase (Auth, FCM)', type: 'opt' }, { id: 'a-publish', label: 'Google Play Publishing', type: 'req' }] }
        ]
    },
    ios: {
        title: 'iOS Developer', sub: 'Step by step guide to becoming an iOS developer',
        nodes: [
            { section: 'Programming Language' },
            { row: [{ id: 'i-swift', label: 'Swift Basics', type: 'req' }, { id: 'i-oop', label: 'OOP & Protocol Oriented', type: 'req' }, { id: 'i-memory', label: 'ARC & Memory Mgmt', type: 'req' }] },
            { section: 'IDE & Tools' },
            { row: [{ id: 'i-xcode', label: 'Xcode', type: 'req' }, { id: 'i-cocoa', label: 'CocoaPods / SPM', type: 'req' }] },
            { section: 'UI Development' },
            { row: [{ id: 'i-swiftui', label: 'SwiftUI (Modern)', type: 'req' }, { id: 'i-uikit', label: 'UIKit (Legacy/Standard)', type: 'req' }, { id: 'i-auto', label: 'Auto Layout', type: 'req' }] },
            { section: 'Data & Networking' },
            { row: [{ id: 'i-url', label: 'URLSession & REST APIs', type: 'req' }, { id: 'i-coredata', label: 'Core Data', type: 'req' }, { id: 'i-userdefs', label: 'UserDefaults', type: 'req' }] },
            { section: 'Architecture' },
            { row: [{ id: 'i-mvc', label: 'MVC', type: 'req' }, { id: 'i-mvvm', label: 'MVVM', type: 'req' }, { id: 'i-combine', label: 'Combine / Async-Await', type: 'req' }] },
            { section: 'Advanced' },
            { row: [{ id: 'i-location', label: 'CoreLocation & MapKit', type: 'opt' }, { id: 'i-notif', label: 'Push Notifications', type: 'req' }, { id: 'i-appstore', label: 'App Store Connect & TestFlight', type: 'req' }] }
        ]
    },
    eamcet: {
        title: 'EAMCET — Engineering', sub: 'Complete roadmap from Inter to engineering career',
        nodes: [
            { section: 'Mathematics' },
            { row: [{ id: 'e-algebra', label: 'Algebra & Trigonometry', type: 'req' }, { id: 'e-calc', label: 'Calculus (Limits, Derivatives)', type: 'req' }, { id: 'e-integration', label: 'Integration', type: 'req' }] },
            { row: [{ id: 'e-coord', label: 'Coordinate Geometry', type: 'req' }, { id: 'e-vectors', label: 'Vectors & 3D', type: 'req' }, { id: 'e-prob', label: 'Probability & Statistics', type: 'req' }] },
            { section: 'Physics' },
            { row: [{ id: 'e-mechanics', label: 'Mechanics', type: 'req' }, { id: 'e-waves', label: 'Waves & Optics', type: 'req' }, { id: 'e-electricity', label: 'Electricity & Magnetism', type: 'req' }] },
            { row: [{ id: 'e-thermo', label: 'Thermodynamics', type: 'req' }, { id: 'e-modern', label: 'Modern Physics', type: 'req' }] },
            { section: 'Chemistry' },
            { row: [{ id: 'e-organic', label: 'Organic Chemistry', type: 'req' }, { id: 'e-inorganic', label: 'Inorganic Chemistry', type: 'req' }, { id: 'e-atomic', label: 'Atomic Structure & Bonding', type: 'req' }] },
            { section: 'Exam Preparation' },
            { row: [{ id: 'e-pyq', label: 'Previous Year Papers', type: 'req' }, { id: 'e-mock', label: 'Mock Tests (Daily)', type: 'req' }, { id: 'e-time', label: 'Time Management', type: 'req' }] },
        ]
    },
    it: {
        title: 'IT Skills — Software Job', sub: 'From zero to first software job without degree',
        nodes: [
            { section: 'Web Fundamentals' },
            { row: [{ id: 'it-html', label: 'HTML & CSS', type: 'req' }, { id: 'it-js', label: 'JavaScript', type: 'req' }, { id: 'it-responsive', label: 'Responsive Design', type: 'req' }] },
            { section: 'Version Control' },
            { row: [{ id: 'it-git', label: 'Git & GitHub', type: 'req' }] },
            { section: 'Frontend Framework' },
            { row: [{ id: 'it-react', label: 'React.js', type: 'req' }, { id: 'it-tailwind', label: 'Tailwind CSS', type: 'req' }] },
            { section: 'Backend' },
            { row: [{ id: 'it-node', label: 'Node.js', type: 'req' }, { id: 'it-sql', label: 'SQL & Database', type: 'req' }, { id: 'it-api', label: 'REST API', type: 'req' }] },
            { section: 'DSA (for interviews)' },
            { row: [{ id: 'it-dsa', label: 'Arrays & Strings', type: 'req' }, { id: 'it-algo', label: 'Sorting & Searching', type: 'req' }, { id: 'it-tree', label: 'Trees & Graphs', type: 'opt' }] },
            { section: 'Job Ready' },
            { row: [{ id: 'it-projects', label: 'Build 3-5 Projects', type: 'req' }, { id: 'it-resume', label: 'Resume & LinkedIn', type: 'req' }, { id: 'it-interview', label: 'Interview Prep', type: 'req' }] },
        ]
    },
    neet: {
        title: 'NEET — Medical', sub: 'Complete roadmap to crack NEET and become a doctor',
        nodes: [
            { section: 'Biology — Botany' },
            { row: [{ id: 'n-cell', label: 'Cell Biology', type: 'req' }, { id: 'n-plant', label: 'Plant Physiology', type: 'req' }, { id: 'n-genetics', label: 'Genetics', type: 'req' }] },
            { section: 'Biology — Zoology' },
            { row: [{ id: 'n-human', label: 'Human Physiology', type: 'req' }, { id: 'n-repro', label: 'Reproduction', type: 'req' }, { id: 'n-eco', label: 'Ecology & Environment', type: 'req' }] },
            { section: 'Chemistry' },
            { row: [{ id: 'n-organic', label: 'Organic Chemistry', type: 'req' }, { id: 'n-inorganic', label: 'Inorganic Chemistry', type: 'req' }, { id: 'n-physical', label: 'Physical Chemistry', type: 'req' }] },
            { section: 'Physics' },
            { row: [{ id: 'n-phymech', label: 'Mechanics', type: 'req' }, { id: 'n-phyoptics', label: 'Optics & Waves', type: 'req' }, { id: 'n-phymodern', label: 'Modern Physics', type: 'req' }] },
            { section: 'Preparation' },
            { row: [{ id: 'n-ncert', label: 'NCERT Textbooks (Cover to Cover)', type: 'req' }, { id: 'n-pyq', label: 'Previous Year Papers', type: 'req' }, { id: 'n-mock', label: 'Mock Tests Daily', type: 'req' }] },
        ]
    },
    appsc: {
        title: 'APPSC — Govt Job', sub: 'Complete guide to APPSC Group exams preparation',
        nodes: [
            { section: 'Language Skills' },
            { row: [{ id: 'a-english', label: 'English Grammar & Comprehension', type: 'req' }, { id: 'a-telugu', label: 'Regional Language', type: 'opt' }] },
            { section: 'Quantitative Aptitude' },
            { row: [{ id: 'a-maths', label: 'Arithmetic', type: 'req' }, { id: 'a-reasoning', label: 'Logical Reasoning', type: 'req' }, { id: 'a-data', label: 'Data Interpretation', type: 'req' }] },
            { section: 'General Studies' },
            { row: [{ id: 'a-history', label: 'Indian & AP History', type: 'req' }, { id: 'a-geography', label: 'Indian & AP Geography', type: 'req' }, { id: 'a-polity', label: 'Indian Polity & Constitution', type: 'req' }] },
            { row: [{ id: 'a-economy', label: 'Indian Economy', type: 'req' }, { id: 'a-science', label: 'General Science', type: 'req' }, { id: 'a-current', label: 'Current Affairs (Daily)', type: 'req' }] },
            { section: 'Exam Prep' },
            { row: [{ id: 'a-pyq', label: 'Previous Year Papers', type: 'req' }, { id: 'a-mock', label: 'Mock Tests (50 Qs Daily)', type: 'req' }, { id: 'a-essay', label: 'Essay & Letter Writing', type: 'req' }] },
        ]
    },
    diploma: {
        title: 'Diploma — Industry Job', sub: 'From polytechnic to first industry job',
        nodes: [
            { section: 'Admission' },
            { row: [{ id: 'di-entrance', label: 'POLYCET Entrance Exam', type: 'req' }, { id: 'di-branch', label: 'Choose Branch (Mech/ECE/Civil)', type: 'req' }] },
            { section: 'Core Studies' },
            { row: [{ id: 'di-workshop', label: 'Workshop & Lab Practice', type: 'req' }, { id: 'di-drawing', label: 'Engineering Drawing', type: 'req' }, { id: 'di-math', label: 'Engineering Mathematics', type: 'req' }] },
            { section: 'Branch Specialization' },
            { row: [{ id: 'di-core', label: 'Core Subject Mastery', type: 'req' }, { id: 'di-lab', label: 'Practical Lab Work', type: 'req' }, { id: 'di-cad', label: 'AutoCAD / Software Tools', type: 'req' }] },
            { section: 'Career Readiness' },
            { row: [{ id: 'di-internship', label: 'Internship (6 months)', type: 'req' }, { id: 'di-resume', label: 'Resume & Interview Prep', type: 'req' }, { id: 'di-job', label: 'First Industry Job', type: 'req' }] },
            { section: 'Further Growth' },
            { row: [{ id: 'di-lateral', label: 'Lateral Entry to B.Tech', type: 'opt' }, { id: 'di-govt', label: 'Govt Jobs (Railway/PSU)', type: 'opt' }] },
        ]
    },
};

// Related roadmaps for sidebar
export const RELATED_ROADMAPS = {
    frontend: ['javascript', 'react', 'fullstack'],
    backend: ['python', 'sql', 'devops', 'docker'],
    react: ['javascript', 'frontend', 'fullstack'],
    javascript: ['react', 'frontend', 'fullstack'],
    python: ['backend', 'aiengineer', 'sql'],
    devops: ['docker', 'backend', 'git'],
    docker: ['devops', 'backend', 'git'],
    git: ['frontend', 'backend', 'devops'],
    sql: ['backend', 'python', 'fullstack'],
    fullstack: ['frontend', 'backend', 'react'],
    aiengineer: ['python', 'backend', 'devops'],
    android: ['kotlin', 'backend', 'git'],
    ios: ['frontend', 'git', 'backend'],
    eamcet: ['it', 'diploma'],
    it: ['frontend', 'backend', 'fullstack'],
    neet: ['eamcet'],
    appsc: ['eamcet', 'neet'],
    diploma: ['it', 'eamcet'],
};

// Role descriptions for "What is [Role]?" section
export const ROLE_INTROS = {
    frontend: 'A Frontend Developer builds the visual and interactive parts of websites and web apps that users see and interact with. They work with HTML, CSS, and JavaScript — and modern frameworks like React or Vue — to create responsive, fast, and beautiful user interfaces.',
    backend: 'A Backend Developer works on the server side — building APIs, managing databases, handling authentication, and making sure data flows correctly between the front-end and the server. They work with languages like Python, Node.js, Java, or Go.',
    react: 'A React Developer specializes in building user interfaces using React.js — the most popular JavaScript library for building single-page applications. They create reusable components, manage complex state, and often work with Next.js for server-side rendering.',
    javascript: 'JavaScript is the programming language of the web. It runs in every browser and powers everything from simple animations to complex full-stack applications. Mastering JavaScript is essential for any web developer.',
    python: 'Python is one of the most versatile programming languages — used in web development, data science, machine learning, automation, and more. Its clean syntax makes it beginner-friendly, while its powerful libraries make it industry-standard.',
    devops: 'A DevOps Engineer bridges the gap between development and operations. They automate deployments, manage cloud infrastructure, set up CI/CD pipelines, and ensure applications run reliably in production at scale.',
    docker: 'Docker is a platform for building, shipping, and running applications in containers. Containers package your app with all its dependencies, ensuring it works the same way everywhere — from your laptop to production.',
    git: 'Git is the industry-standard version control system. It tracks changes to your code, enables collaboration with teams, and lets you manage multiple branches of development. GitHub is the most popular platform for hosting Git repositories.',
    sql: 'SQL (Structured Query Language) is the standard language for working with relational databases. It lets you store, retrieve, update, and analyze data — an essential skill for any developer or data professional.',
    fullstack: 'A Full Stack Developer can build both the frontend (what users see) and backend (server, database, APIs) of web applications. They understand the entire web development pipeline from design to deployment.',
    aiengineer: 'An AI Engineer builds intelligent systems using machine learning, deep learning, and large language models. They work with Python, PyTorch/TensorFlow, and modern tools like LangChain to create AI-powered applications.',
    android: 'An Android Developer builds mobile applications for Android devices using Kotlin (or Java) and Android Studio. They work with Jetpack Compose for modern UI, Room for databases, and publish apps to the Google Play Store.',
    ios: 'An iOS Developer builds mobile applications for iPhones and iPads using Swift and Xcode. They use SwiftUI and UIKit for user interfaces and follow Apple\'s Human Interface Guidelines.',
    eamcet: 'EAMCET (Engineering, Agriculture and Medical Common Entrance Test) is a state-level entrance exam for admission into engineering and medical colleges in Andhra Pradesh and Telangana.',
    it: 'This roadmap is for anyone — with or without a CS degree — who wants to land their first software/IT job. It covers the essential web development, programming, and interview skills you need.',
    neet: 'NEET (National Eligibility cum Entrance Test) is the entrance exam for admission to MBBS, BDS, and other medical courses across India. It tests Physics, Chemistry, and Biology.',
    appsc: 'APPSC (Andhra Pradesh Public Service Commission) conducts recruitment exams for government jobs in AP. This roadmap covers General Studies, Aptitude, and exam preparation strategies.',
    diploma: 'This roadmap guides Diploma/Polytechnic students from their studies through to landing their first industry job — covering core subjects, practical skills, internships, and career preparation.',
};

export const SIMPLE_ROADMAPS = [];
export const SIMPLE_NAMES = {};
export const ROADMAP_DATA = DETAIL_DEFS;
